site_name: P4OO.py
copyright: Copyright (C) 2011-2015,2024 by David L. Armstrong, Cisco Systems, Inc.
repo_url: https://github.com/DaverSomethingSomethingOrg/P4OO.py
site_url: https://daversomethingsomethingorg.github.io/P4OO.py/
#edit_uri_template: 'edit/main/docs/{path}'
docs_dir: docs/

plugins:
  - techdocs-core

markdown_extensions:
  - toc:
      permalink: \#
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  