site_name: P4OO.py
copyright: Copyright (C) 2011-2015,2024 by David L. Armstrong, Cisco Systems, Inc.
repo_url: https://github.com/DaverSomethingSomethingOrg/P4OO.py
site_url: https://daversomethingsomethingorg.github.io/P4OO.py/
edit_uri_template: 'edit/main/docs/{path}'
docs_dir: docs/

plugins:
  - techdocs-core
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
#            inherited_members: true
            filters:
              - "!^__"

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - toc:
      permalink: '#'
      toc_depth: 4
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts

watch:
  - docs/
  - src/

nav:
  - 'index.md'
  - 'About P4OO.py': 'about.md'
  - 'howto.md'
  - 'API Reference':
    - 'P4OOBranch.md'
    - 'P4OOChange.md'
    - 'P4OOClient.md'
    - 'P4OOCounter.md'
    - 'P4OODepot.md'
    - 'P4OOFile.md'
    - 'P4OOGroup.md'
    - 'P4OOJob.md'
    - 'P4OOLabel.md'
    - 'P4OOUser.md'
    - 'specobjs.md'
    - 'setobjs.md'
    - 'internals.md'
    - 'exceptions.md'
  - 'Unit Test Coverage Report': 'coverage/index.html'
  - 'Pylint Report': 'pylint.html'
