%YAML 1.2
---
######################################################################
#  Copyright (c)2011-2012,2015,2024 David L. Armstrong.
#  Copyright (c)2012-2013 David L. Armstrong and Cisco Systems, Inc.
#
#  p4Config.yml
#
######################################################################

# p4Config.yml configures P4OO to talk to P4Python and P4PERL,
# describing the command syntax supported per command, and what
# to do with the results of executing Perforce commands.

COMMANDS:
  branch:
    specCmd: branch
    idAttr: branch
    idRequired: True
    p4ooType: Branch
    specAttrs:
      description: Description
      branch: Branch
      owner: Owner
      options: Options
      view: View
    dateAttrs:
      update: Update
      access: Access
    forceOption: -f
  branches:
    output:
      idAttr: branch
      p4ooType: Branch
    queryOptions:
      user: &branches_user
        type: [ string, User ]
        option: -u
        multiplicity: 1
      owner: *branches_user
      namefilter:
        type: [ string ]
        option: -e
        multiplicity: 1
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1


  change: &change
    specCmd: change
    idAttr: change
    idRequired: True
    p4ooType: Change
    specAttrs:
      change: Change
      client: Client
      description: Description
      user: User
      status: Status
      type: Type
      jobs: Jobs
      files: Files
    dateAttrs:
      date: Date
    forceOption: -f
  changes: &changes
    output:
      idAttr: change
      p4ooType: Change
    queryOptions:
      user: &changes_user
        type: [ string, User ]
        option: -u
        multiplicity: 1
      owner: *changes_user
      client:
        type: [ string, Client ]
        option: -c
        multiplicity: 1
      status:
        type: [ string ]
        option: -s
        multiplicity: 1
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      longoutput:
        option: -l
        multiplicity: 0
      files:
        type: [ string, File, FileSet ]


  # Changelist is the same as Change
  changelist: *change
  changelists: *changes


  client: &client
    specCmd: client
    idAttr: client
    idRequired: False
    p4ooType: Client
    specAttrs:
      client: Client
      owner: Owner
      host: Host
      description: Description
      root: Root
      altroots: AltRoots
      options: Options
      submitoptions: SubmitOptions
      lineend: LineEnd
      view: View
    dateAttrs:
      update: Update
      access: Access
    forceOption: -f
  clients: &clients
    output:
      idAttr: client
      p4ooType: Client
    queryOptions:
      user: &clients_user
        type: [ string, User ]
        option: -u
        multiplicity: 1
      owner: *clients_user
      namefilter:
        type: [ string ]
        option: -e
        multiplicity: 1
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1

  # Workspace is the same as Client
  workspace: *client
  workspaces: *clients


  depot:
    specCmd: depot
    idAttr: depot
    idRequired: True
    p4ooType: Depot
    specAttrs:
      depot: Depot
      owner: Owner
      description: Description
      type: Type
      address: Address
      suffix: Suffix
      map: Map
    dateAttrs:
      date: Date
  depots:
    output:
      idAttr: depot
      p4ooType: Depot
    queryOptions:
      depottype:
        type: [ string ]
        option: -t
        multiplicity: 1
      namefilter:
        type: [ string ]
        option: -e
        multiplicity: 1


  group:
    specCmd: group
    idAttr: group
    idRequired: True
    p4ooType: Group
    specAttrs:
      group: Group
      owners: Owners
      users: Users
      maxresults: MaxResults
      maxscanrows: MaxScanRows
      maxlocktime: MaxLockTime
      maxopenfiles: MaxOpenFiles
      maxmemory: MaxMemory
      sessiontimeout: Timeout
      passwordtimeout: PasswordTimeout
      subgroups: Subgroups
    forceOption: -f
  groups:
    output:
      idAttr: group
      p4ooType: Group
    queryOptions:
      group:
        type: [ string, Group ]
        option: -g
        multiplicity: 1
      member:
        type: [ string, User ]
        option: -u
        multiplicity: 1
      owner:
        type: [ string, User ]
        option: -o
        multiplicity: 1
      indirect:
        type: [ string, User, Group ]
        option: -i
        multiplicity: 1
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1


  job:
    specCmd: job
    idAttr: job
    idRequired: False
    p4ooType: Job
    specAttrs:
      job: Job
      status: Status
      user: User
      description: Description
    dateAttrs:
      date: Date
    forceOption: -f
  jobs:
    output:
      idAttr: job
      p4ooType: Job
    queryOptions:
      jobview:
        type: [ string ]
        option: -e
        multiplicity: 1
      longoutput:
        option: -l
        multiplicity: 0
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]


  label:
    specCmd: label
    idAttr: label
    idRequired: True
    p4ooType: Label
    specAttrs:
      label: Label
      owner: Owner
      description: Description
      options: Options
      revision: Revision
      view: View
    dateAttrs:
      update: Update
      access: Access
    forceOption: -f
  labels:
    output:
      idAttr: label
      p4ooType: Label
    queryOptions:
      user: &labels_user
        type: [ string, User ]
        option: -u
        multiplicity: 1
      owner: *labels_user
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      namefilter:
        type: [ string ]
        option: -e
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]


  user:
    specCmd: user
    idAttr: user
    idRequired: False
    p4ooType: User
    specAttrs:
      user: User
      email: Email
      fullname: FullName
      jobview: JobView
      password: Password
      reviews: Reviews
    dateAttrs:
      update: Update
      access: Access
    forceOption: -f
  users:
    output:
      idAttr: User
      p4ooType: User
    queryOptions:
      maxresults:
        type: [ string ]
        option: -m
        multiplicity: 1
      allusers:
        option: -a
        multiplicity: 0
      longoutput:
        option: -l
        multiplicity: 0
      users:
        type: [ string, User, UserSet ]


# other p4 commands that don't return specs natively
  counter:
    specCmd: counter
    idAttr: counter
    idRequired: True
  counters:
    output:
      idAttr: counter
      p4ooType: Counter
    queryOptions:
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      namefilter:
        type: [ string ]
        option: -e
        multiplicity: 1

#TODO
###subcommands:
### increment
### delete
### set

  # p4 describe [-d<flags> -s -S -f] changelist# ...
  describe:
    output:
      idAttr: change
      p4ooType: Change
    queryOptions:
      diffoptions:
        type: [ string ]
        option: -d
        multiplicity: 1
        bundledArgs: 1
      omitdiffs:
        option: -s
        multiplicity: 0
      shelved:
        option: -S
        multiplicity: 0
      force:
        option: -f
        multiplicity: 0
      changes:
        type: [ string, Change, ChangeSet ]


  # p4 diff [-d<flags> -f -m maxresults -s<flag> -t] [file[rev] ...]
  diff:
    output:
      idAttr: clientFile
      p4ooType: File
    queryOptions:
      diffOptions:
        type: [ string ]
        option: -d
        multiplicity: 1
        bundledArgs: 1
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      missingonclient:
        option: -sd
        multiplicity: 0
      unopenedstatus:
        option: -sl
        multiplicity: 0
      diffbinary:
        option: -t
        multiplicity: 0
      diffallfiles:
        option: -f
        multiplicity: 0
      files:
        type: [ string, File, FileSet ]


  # p4 diff2 [ -d<flags> -q -t -u ] file1 file2
  # p4 diff2 [ -d<flags> -q -t -u ] -b branch [ [ file1 ] file2 ]
  diff2:
    config:
      tagged: 0
    output:
      idAttr: depotFile
      p4ooType: File
    queryOptions:
      branch:
        type: [ string, Branch ]
        option: -b
        multiplicity: 1
      diffoptions:
        type: [ string ]
        option: -d
        multiplicity: 1
        bundledArgs: 1
      omitdiffs:
        option: -q
        multiplicity: 0
      diffbinary:
        option: -t
        multiplicity: 0
      unifieddiff:
        option: -u
        multiplicity: 0
      files:
        type: [ string, File, FileSet ]


  # p4 files [ -a ] [ -A ] [ -m maxresults ] file[revRange] ...
  files:
    output:
      idAttr: depotFile
      p4ooType: File
    queryOptions:
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      archived:
        option: -A
        multiplicity: 0
      allrevisions:
        option: -a
        multiplicity: 0
      excludeDeleted:
        option: -e
        multiplicity: 0
      files:
        type: [ string, File, FileSet ]


  # p4 have [file ...]
  have:
    output:
      idAttr: depotFile
      p4ooType: File
    queryOptions:
      files:
        type: [ string, File, FileSet ]


  # p4 info [-s]
  info:
    queryOptions:
      shortoutput:
        option: -s
        multiplicity: 0

  # p4 interchanges [options] fromFile[revRange] toFile
  # p4 interchanges [options] -b branch [toFile[revRange] ...]
  # p4 interchanges [options] -b branch -s fromFile[revRange] [toFile ...]
  interchanges:
    output:
      idAttr: change
      p4ooType: Change
    queryOptions:
      branch:
        type: [ string, Branch ]
        option: -b
        multiplicity: 1
      change:
        type: [ integer, Change ]
        option: -C
        multiplicity: 1
      reversemap:
        option: -r
        multiplicity: 0
      showtime:
        option: -s
        multiplicity: 0
      longoutput:
        option: -l
        multiplicity: 0
      listfiles:
        option: -f
        multiplicity: 0
      files:
        type: [ string, File, FileSet ]


  # p4 add [-c changelist#] [-d -f -I -n] [-t filetype] file ...
  add:
    configOptions:
      p4client:
        type: [ string, Client ]
#TODO err what does option do here?
        option: client
        multiplicity: 1
    queryOptions:
      change:
        type: [ integer, Change ]
        option: -c
        multiplicity: 1
      reopen:
        option: -d
        multiplicity: 0
      force:
        option: -f
        multiplicity: 0
      no_ignore:
        option: -I
        multiplicity: 0
      preview:
        option: -n
        multiplicity: 0
      file_type:
        type: [ string ]
        option: -t
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]


  # p4 edit [-c changelist#] [-k -n] [-t filetype] [--remote=rmt] file ...
  # p4 edit [-c changelist#] -So
  edit:
    configOptions:
      p4client:
        type: [ string, Client ]
#TODO err what does option do here?
        option: client
        multiplicity: 1
    queryOptions:
      change:
        type: [ integer, Change ]
        option: -c
        multiplicity: 1
      no_pull:
        option: -k
        multiplicity: 0
      preview:
        option: -n
        multiplicity: 0
      file_type:
        type: [ string ]
        option: -t
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]

  # p4 opened [-a -c changelist# -C client -u user -m maxresults] [file ...]
  opened:
    output:
      idAttr: clientFile
      p4ooType: File
    queryOptions:
      allclients:
        option: -a
        multiplicity: 0
      change:
        type: [ integer, Change ]
        option: -c
        multiplicity: 1
      client:
        type: [ string, Client ]
        option: -C
        multiplicity: 1
      user:
        type: [ string, User ]
        option: -u
        multiplicity: 1
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]

  # p4 submit [-r -s -f option -K [-b | --noretransfer 0|1]]
  #           [--parallel=threads=N[,batch=N][,min=N]]
  # p4 submit [-r -s -f option -K -b]
  #           [--parallel=threads=N[,batch=N][,min=N]]
  #           file ...
  # p4 submit [-r -f option -K -b] [-So|-Sx] -d description
  #           [--parallel=threads=N[,batch=N][,min=N]]
  # p4 submit [-r -f option -K -b] [-Sx] -d description
  #           [--parallel=threads=N[,batch=N][,min=N]]
  #           file ...
  # p4 submit [-r -f option -K [-b | --noretransfer 0|1]] -c changelist#
  #           [--parallel=threads=N[,batch=N][,min=N]]
  # p4 submit -e shelvedChange# [-b]
  #           [--parallel=threads=N[,batch=N][,min=N]]
  # p4 submit -i [-r -s -f option -K -b]
  #           [--parallel=threads=N[,batch=N][,min=N]]
  submit:
#    output:
#      idAttr:
#      p4ooType:
    configOptions:
      p4client:
        type: [ string, Client ]
        option: client
        multiplicity: 1
    queryOptions:
      description:
        type: [ string ]
        option: -d
        multiplicity: 1
      change:
        type: [ integer, Change ]
        option: -c
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]


  # p4 sync [-f -n -k -q ] [-m maxresults] [file[revRange] ...]
  # p4 sync [-n -p -q] [-m maxresults] [file[revRange] ...]
  sync:
#    output:
#      idAttr: clientFile
#      p4ooType: File
    configOptions:
      p4client:
        type: [ string, Client ]
        option: client
        multiplicity: 1
    queryOptions:
      force:
        option: -f
        multiplicity: 0
      server_update:
        option: -k
        multiplicity: 0
      populate_only:
        option: -p
        multiplicity: 0
      quiet:
        option: -q
        multiplicity: 0
      preview:
        option: -n
        multiplicity: 0
      maxresults:
        type: [ integer ]
        option: -m
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]


  # p4 reopen [ -c changelist# ] [ -t filetype ] file ...
  reopen:
    configOptions:
      p4client:
        type: [ string, Client ]
        option: client
        multiplicity: 1
    queryOptions:
      change:
        type: [ string, Change ]
        option: -c
        multiplicity: 1
      filetype:
        type: [ string ]
        option: -t
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]

  # p4 revert [ -a -n -k -c changelist# ] file ...
  revert:
    configOptions:
      p4client:
        type: [ string, Client ]
        option: client
        multiplicity: 1
    queryOptions:
      change:
        type: [ string, Change ]
        option: -c
        multiplicity: 1
      noclientrefresh:
        option: -k
        multiplicity: 0
      files:
        type: [ string, File, FileSet ]

  # p4 shelve [ files ]
  # p4 shelve -i [ -f | -r ]
  # p4 shelve -r -c changelist#
  # p4 shelve -c changelist# [ -f ] [ file ... ]
  # p4 shelve -d -c changelist# [ -f ] [ file ... ]
  shelve:
    configOptions:
      p4client:
        type: [ string, Client ]
        option: client
        multiplicity: 1
    queryOptions:
      change:
        type: [ string, Change ]
        option: -c
        multiplicity: 1
      delete:
        option: -d
        multiplicity: 0
      replace:
        option: -r
        multiplicity: 0
      force:
        option: -f
        multiplicity: 0
      files:
        type: [ string, File, FileSet ]

  # p4 tag [-d -g -n -U] -l label file[revRange] ...
  tag:
    configOptions:
      p4client:
        type: [ string, Client ]
        option: client
        multiplicity: 1
    queryOptions:
      delete:
        option: -d
        multiplicity: 0
      global:
        option: -g
        multiplicity: 0
      preview:
        option: -n
        multiplicity: 0
      auto_reload:
        option: -U
        multiplicity: 0
      label:
        type: [ string, Label ]
        option: -l
        multiplicity: 1
      files:
        type: [ string, File, FileSet ]
